// Automatically generated by astro-icon
// 0e1818f24419fceb9797cad4403e83cfbba5a9c9b3236a36c1f4a2910c3e1c65

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "github"
		| "linkedin"
		| "twitter";
}